= Oracle Database 12c Release 1 (12.1) Installation On Oracle Linux 7 (OL7)
Кархачев Роман <roman@aviacons.ru>
:doctype: article
:encoding: utf-8
:lang: ru
:toc: left
:homepage: http://www.aviacons.ru
:experimental:

Oracle Linux 7 is a production release, but Oracle Database 12c is only supported on it from (12.1.0.2) onward. This installation should not be used for a real system when using 12c database versions prior to 12.1.0.2.

This article describes the installation of Oracle Database 12c Release 1 (12.1) 64-bit on Oracle Linux 7 (OL7) 64-bit. The article is based on a server installation with a minimum of 2G swap and secure Linux set to permissive. An example of this type of Linux installation can be seen here.

== Download Software

Download the Oracle software from OTN or MOS depending on your support status.

* http://www.oracle.com/technetwork/database/enterprise-edition/downloads/index.html[OTN: Oracle Database 12c Release 1 (12.1.0.2) Software (64-bit).]
* http://edelivery.oracle.com/[edelivery: Oracle Database 12c Release 1 (12.1.0.2) Software (64-bit)]

== Unpack Files

Unzip the files.
[source,bash]
-----------------
unzip linuxamd64_12102_database_1of2.zip
unzip linuxamd64_12102_database_2of2.zip
-----------------
You should now have a single directory called "database" containing installation files.

== Hosts File

The "/etc/hosts" file must contain a fully qualified name for the server.
[source,bash]
-----------------
<IP-address>  <fully-qualified-machine-name>  <machine-name>
-----------------

.For example.
[source,bash]
-----------------
127.0.0.1       localhost localhost.localdomain localhost4 localhost4.localdomain4
192.168.0.215   ol7.localdomain  ol7
-----------------

Set the correct hostname in the "/etc/hostname" file.

[source,bash]
-----------------
ol7.localdomain
-----------------

== Oracle Installation Prerequisites

Perform either the Automatic Setup or the Manual Setup to complete the basic prerequisites. The Additional Setup is required for all installations.

=== Automatic Setup

If you plan to use the "oracle-rdbms-server-12cR1-preinstall" package to perform all your prerequisite setup, issue the following command.

[source,bash]
-----------------
# yum install oracle-rdbms-server-12cR1-preinstall -y
-----------------

[NOTE]
====
Earlier versions of Oracle Linux required manual setup of the Yum repository by following the instructions at http://public-yum.oracle.com/[http://public-yum.oracle.com].
====

It is probably worth doing a full update as well, but this is not strictly speaking necessary.

[source,bash]
-----------------
# yum update -y
-----------------

[NOTE]
====
It's worth running the all the YUM commands listed in the manual setup section. Depending on the OS package groups you have selected, some additional packages might also be needed.
====

=== Manual Setup

If you have not used the "oracle-rdbms-server-12cR1-preinstall" package to perform all prerequisites, you will need to manually perform the following setup tasks.

Add the following lines to the "/etc/sysctl.conf" file, or in a file called "/etc/sysctl.d/98-oracle.conf".

[source,bash]
-----------------
fs.file-max = 6815744
kernel.sem = 250 32000 100 128
kernel.shmmni = 4096
kernel.shmall = 1073741824
kernel.shmmax = 4398046511104
kernel.panic_on_oops = 1
net.core.rmem_default = 262144
net.core.rmem_max = 4194304
net.core.wmem_default = 262144
net.core.wmem_max = 1048576
net.ipv4.conf.all.rp_filter = 2
net.ipv4.conf.default.rp_filter = 2
fs.aio-max-nr = 1048576
net.ipv4.ip_local_port_range = 9000 65500
-----------------

Run the following command to change the current kernel parameters.

[source,bash]
-----------------
/sbin/sysctl -p
-----------------

Add the following lines to a file called "/etc/security/limits.d/oracle-rdbms-server-12cR1-preinstall.conf" file.
[source,bash]
-----------------
oracle   soft   nofile    1024
oracle   hard   nofile    65536
oracle   soft   nproc    16384
oracle   hard   nproc    16384
oracle   soft   stack    10240
oracle   hard   stack    32768
oracle   hard   memlock    134217728
oracle   soft   memlock    134217728
-----------------

The following packages are listed as required, including the 32-bit version of some of the packages. Many of the packages should be installed already.

[source,bash]
-----------------
yum install binutils -y
yum install compat-libstdc++-33 -y
yum install compat-libstdc++-33.i686 -y
yum install gcc -y
yum install gcc-c++ -y
yum install glibc -y
yum install glibc.i686 -y
yum install glibc-devel -y
yum install glibc-devel.i686 -y
yum install ksh -y
yum install libgcc -y
yum install libgcc.i686 -y
yum install libstdc++ -y
yum install libstdc++.i686 -y
yum install libstdc++-devel -y
yum install libstdc++-devel.i686 -y
yum install libaio -y
yum install libaio.i686 -y
yum install libaio-devel -y
yum install libaio-devel.i686 -y
yum install libXext -y
yum install libXext.i686 -y
yum install libXtst -y
yum install libXtst.i686 -y
yum install libX11 -y
yum install libX11.i686 -y
yum install libXau -y
yum install libXau.i686 -y
yum install libxcb -y
yum install libxcb.i686 -y
yum install libXi -y
yum install libXi.i686 -y
yum install make -y
yum install sysstat -y
yum install unixODBC -y
yum install unixODBC-devel -y
yum install zlib-devel -y
yum install zlib-devel.i686 -y
-----------------

Create the new groups and users.

[source,bash]
-----------------
groupadd -g 54321 oinstall
groupadd -g 54322 dba
groupadd -g 54323 oper
#groupadd -g 54324 backupdba
#groupadd -g 54325 dgdba
#groupadd -g 54326 kmdba
#groupadd -g 54327 asmdba
#groupadd -g 54328 asmoper
#groupadd -g 54329 asmadmin

useradd -u 54321 -g oinstall -G dba,oper oracle
-----------------

Uncomment the extra groups you require.

== Additional Setup

The following steps must be performed, whether you did the manual or automatic setup.

Set the password for the "oracle" user.

[source,bash]
-----------------
passwd oracle
-----------------

Set secure Linux to permissive by editing the "/etc/selinux/config" file, making sure the SELINUX flag is set as follows.

[source,bash]
-----------------
SELINUX=permissive
-----------------

Once the change is complete, restart the server or run the following command.

[source,bash]
-----------------
# setenforce Permissive
-----------------

If you have the Linux firewall enabled, you will need to disable or configure it, as shown https://oracle-base.com/articles/linux/oracle-linux-6-installation#firewall[here] or https://oracle-base.com/articles/linux/linux-firewall#installation[here]. To disable it, do the following.

[source,bash]
-----------------
# systemctl stop firewalld
# systemctl disable firewalld
-----------------

Create the directories in which the Oracle software will be installed.

[source,bash]
-----------------
mkdir -p /u01/app/oracle/product/12.1.0.2/db_1
chown -R oracle:oinstall /u01
chmod -R 775 /u01
-----------------

[NOTE]
====
Putting mount points directly under root is typically a bad idea. It's done here for simplicity, but for a real installation "/" should be reserved for the OS.
====

Unless you are working from the console, or using SSH tunnelling, login as root and issue the following command.

[source,bash]
-----------------
xhost +<machine-name>
-----------------

Add the following lines at the end of the "/home/oracle/.bash_profile" file.

[source,bash]
-----------------
# Oracle Settings
export TMP=/tmp
export TMPDIR=$TMP

export ORACLE_HOSTNAME=ol7.localdomain
export ORACLE_UNQNAME=cdb1
export ORACLE_BASE=/u01/app/oracle
export ORACLE_HOME=$ORACLE_BASE/product/12.1.0.2/db_1
export ORACLE_SID=cdb1

export PATH=/usr/sbin:$PATH
export PATH=$ORACLE_HOME/bin:$PATH

export LD_LIBRARY_PATH=$ORACLE_HOME/lib:/lib:/usr/lib
export CLASSPATH=$ORACLE_HOME/jlib:$ORACLE_HOME/rdbms/jlib
-----------------

== Installation

Log into the oracle user. If you are using X emulation then set the DISPLAY environmental variable.

[source,bash]
-----------------
DISPLAY=<machine-name>:0.0; export DISPLAY
-----------------

Start the Oracle Universal Installer (OUI) by issuing the following command in the database directory.

[source,bash]
-----------------
./runInstaller
-----------------

Proceed with the installation of your choice.

[NOTE]
====
If you are doing an installation for an Enterprise Manager repository, remember to do an advanced installation and pick the ALT32UTF8 character set.
====

Check out the notes below for how to deal with potential errors that may arise during the installation.

You can see the type of installation I performed by clicking on the links below to see screen shots of each stage.

== Post Installation

Edit the "/etc/oratab" file setting the restart flag for each instance to 'Y'.

[source,bash]
-----------------
cdb1:/u01/app/oracle/product/12.1.0.2/db_1:Y
-----------------

== 12.1.0.1 Notes

Only follow these notes if you are attempting the install using 12.1.0.1, there are a number of things that will need to be fixed along the way. These are not necessary for a 12.1.0.2 installation, as it completes cleanly.

The following steps need to be considered during the installation.

* When clicking "Next" on the "Download Software Updates" screen you will get the following message. Click the "Yes" button.
+
[source]
-----------------
"[INS-13001] Environment does not meet minimum requirements.
Are you sure you want to continue?
-----------------
+

* During the linking phase, you will see the following error.
+
[source]
-----------------
Error in invoking target 'links proc gen_pcscfg procob' of makefile
'/u01/app/oracle/product/12.1.0.1/db_1/precomp/lib/ins_precomp.mk'.
See
'/u01/app/oraInventory/logs/installActions2014-04-26_08-07-04PM.log'
for details.
-----------------
+
To fix it, do the following:
+
[source,bash]
-----------------
rm -rf $ORACLE_HOME/lib/stubs/*
cp $ORACLE_HOME/rdbms/lib/env_rdbms.mk $ORACLE_HOME/rdbms/lib/env_rdbms.mk.orig
-----------------
+
Perform the following modifications to the "$ORACLE_HOME/rdbms/lib/env_rdbms.mk" file.
+
[source,bash]
-----------------
# Line 176
# FROM:
LINKTTLIBS=$(LLIBCLNTSH) $(ORACLETTLIBS) $(LINKLDLIBS)
# TO  :
LINKTTLIBS=$(LLIBCLNTSH) $(ORACLETTLIBS) $(LINKLDLIBS) -lons

# Line 279-280
# FROM:
LINK=$(FORT_CMD) $(PURECMDS) $(ORALD) $(LDFLAGS) $(COMPSOBJS)
LINK32=$(FORT_CMD) $(PURECMDS) $(ORALD) $(LDFLAGS32) $(COMPSOBJS)
# TO  :
LINK=$(FORT_CMD) $(PURECMDS) $(ORALD) $(LDFLAGS) $(COMPSOBJS) -Wl,--no-as-needed
LINK32=$(FORT_CMD) $(PURECMDS) $(ORALD) $(LDFLAGS32) $(COMPSOBJS) -Wl,--no-as-needed

# Line 3041-3042
# FROM:
TG4PWD_LINKLINE= $(LINK) $(OPT) $(TG4PWDMAI) \
        $(LLIBTHREAD) $(LLIBCLNTSH) $(LINKLDLIBS)
# TO  :
TG4PWD_LINKLINE= $(LINK) $(OPT) $(TG4PWDMAI) \
        $(LLIBTHREAD) $(LLIBCLNTSH) $(LINKLDLIBS) -lnnz12
-----------------
+
Click the "Retry" button.

* Later, you might see the following error.
+
[source]
-----------------
Error in invoking target 'install' of makefile 
'/u01/app/oracle/product/12.1.0.1/db_1/ctx/lib/ins_ctx.mk'.
See
'/u01/app/oraInventory/logs/installActions2014-04-26_08-07-04PM.log'
for details.
-----------------
+
To fix it, do the following:
+
[source,bash]
-----------------
rm -rf $ORACLE_HOME/lib/stubs/*
cp $ORACLE_HOME/ctx/lib/env_ctx.mk $ORACLE_HOME/ctx/lib/env_ctx.mk.orig
-----------------
+
Perform the following modifications to the "$ORACLE_HOME/ctx/lib/env_ctx.mk" file.
+
[source,bash]
-----------------
# Line 154
# FROM:
LINK=$(LDCCOM)
# TO  :
LINK=$(LDCCOM) --Wl,--no-as-needed
-----------------
+
Click the "Retry" button.

Due to the issues during the linking phase, it probably makes sense to do a relink once the installation is complete.

[source,bash]
-----------------
dbshut $ORACLE_HOME
cd $ORACLE_HOME/bin
./relink all
# Following line should return no errors.
grep -i err $ORACLE_HOME/install/relink.log
dbstart $ORACLE_HOME
-----------------

== 12.1.0.2 Notes

During the linking phase, you may see the following error.

[source]
-----------------
Error in invoking target 'irman ioracle' of makefile '/u01/app/oracle/product/12.1.0.2/db_1/rdbms/lib/ins_rdbms.mk'
-----------------

To fix it, run the following command as the "oracle" user, then click the "Retry" button.

[source,bash]
-----------------
cp  $ORACLE_HOME/javavm/jdk/jdk6/lib/libjavavm12.a $ORACLE_HOME/lib/
-----------------

During the database creation as part of the installation, or after when using the DBCA, you may get the following error.

[source]
-----------------
Error while executing "/u01/app/oracle/product/12.1.0.2/db_1/rdbms/admin/dbmssml.sql". Refer to "/u01/app/oracle/cfgtoollogs/dbca/orcl/dbmssml0.log" for more details. Error in Process: /u01/app/oracle/product/12.1.0.2/db_1/perl/bin/perl
-----------------

To fix it, follow the instructions to rebuild Perl as described towards the end of this http://laurent-leturgez.com/2015/05/26/oracle-12c-vmware-fusion-and-the-perl-binarys-segmentation-fault/[post by Laurent Leturgez]. You will have to redo the database creation.

For more information see:

* http://docs.oracle.com/database/121/LADBI/toc.htm[Oracle Database Installation Guide 12c Release 1 (12.1) for Linux]
* https://oracle-base.com/articles/linux/automating-database-startup-and-shutdown-on-linux[Automating Database Startup and Shutdown on Linux]

Hope this helps. Regards Tim...
